services:
  backend:
    image: aspnetcoreconfiguration
    build:
      context: .
      dockerfile: AspNetCoreConfiguration/Dockerfile
    environment:
      - CONNECTIONSTRINGS__DEFAULT=Server=db;User Id=sa;Password=Password123;Encrypt=False;
    ports:
      - 8080:8080
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    ports:
      - 1433:1433